service:
  port: 8080

spring:
  datasource:
    name: hoteldata
    url: jdbc:mysql://localhost:3306/hoteldata?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false

devtools:
    restart:
    #热部署生效
    enabled: true
    #设置重启的目录
    additional-paths: resources/**,static/**,templates/**



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xmut.hotel.entity

